name: Dusk
favicon: null
layout_spectrum: 0.50668
typography_spectrum: 0.5
title: Dusk is the creative output of Rhys Jones
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#111e2b'
    - '#2b4b55'
    - '#609dbf'
    - '#517d81'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
